### ISSUE TITLE
get started button on homepage returns 404 

### ISSUE THREAD

**Issue by jaeivan** [ucf-senior-design/senior-design#118]
When you click the get started button on the homepage you don't get rerouted to the register page. I think it is because of the capitalization of the route.

/auth/register vs. /Auth/Register

**Comment by jonathanhuydieu** [comment]
Looking into this... 👀

**Comment by jonathanhuydieu** [comment]
I just spent an hour wondering why TF setting up a single unit test to test the register endpoint wasn't working at all to find out that our register endpoint actually _overrides the inbuilt nextjs request type with a custom request that holds user information_ 😭 
<img width="1598" alt="image" src="https://user-images.githubusercontent.com/59897679/221380435-1bee4886-7e7f-4426-8ff9-a70b0d75a645.png">

**Comment by Nin3s** [comment]
oh yeah the pages were renamed so some of the buttons might need to be changed as well lol sry

**Comment by jonathanhuydieu** [comment]
you're good it works now I just can't seem to write the stupid test properly

**Comment by Nin3s** [comment]
L
