### ISSUE TITLE
Registering with Google Auth SSO links to the wrong URL

### ISSUE THREAD

**Issue by jonathanhuydieu** [ucf-senior-design/senior-design#220]
When registering as a new user with Google Auth, it directs the user to `https://we-tinerary.vercel.app/auth/auth/details` instead of `https://we-tinerary.vercel.app/auth/details`, which results in a `404 NOT FOUND`. Seems like there may be a small bug somewhere that's appending `auth/details` to an endpoint that already has `auth` at the end (or vice versa)

Image attached for reference:
<img width="668" alt="image" src="https://user-images.githubusercontent.com/59897679/230540739-20cb86f5-5ad2-4885-b66f-6c50810c933e.png">

**Comment by Nin3s** [comment]
https://github.com/ucf-senior-design/senior-design/tree/thirdpartyauth-bugfix
