### ISSUE TITLE
Can't sign into web app

### ISSUE THREAD

**Issue by aamare1001** [ucf-senior-design/senior-design#244]
![image](https://user-images.githubusercontent.com/26231761/231493414-61ead6a2-65d0-412c-a60b-b405a41d94e0.png)
![image](https://user-images.githubusercontent.com/26231761/231495077-5defc724-4490-4fbe-b6bd-204772679a43.png)

Site doesn't let me sign in. When clicking any page(except logout) i'm asked to put account details although this is an old account and a blank error occurs upon continue

**Comment by aamare1001** [comment]
The info is changing in the database after continue

**Comment by jonathanhuydieu** [comment]
Can confirm- this issue seems to be specifically with logging in, as registering with a new account works (new user is successfully created in Firebase) but trying to log in with those credentials results in the error shown above.
