### ISSUE TITLE
Nit: Fix "poll must have options message in suggestion"

### ISSUE THREAD

**Issue by jonathanhuydieu** [ucf-senior-design/senior-design#256]
When creating a new suggestion, there's a toast error message upon creation that looks like it was reused from the poll widget, saying that it's missing `options`. Most likely a check that made it's way in via copypasta. Screenshot attached for reference.

<img width="807" alt="image" src="https://user-images.githubusercontent.com/59897679/231667121-38c85336-2af5-4510-a0c2-67bb74608ef1.png">

**Comment by aamare1001** [comment]
Have you entered options and clicked enter after?

**Comment by jonathanhuydieu** [comment]
> Have you entered options and clicked enter after?

@aamare1001 There's nowhere to enter options 😭

**Comment by jonathanhuydieu** [comment]
WAIT I JUST GOT WHAT YOU MEAN LIKE LITERALLY HIT THE `ENTER` KEY 💀 Pls ignore me I am but a fool in a man's shoes 🤡
