### ISSUE TITLE
Joinable event shows for everyone if >1 person is attending

### ISSUE THREAD

**Issue by aamare1001** [ucf-senior-design/senior-design#261]
![image](https://user-images.githubusercontent.com/26231761/231936224-8854b547-58b5-49ca-aaec-5e78445e20fd.png)
![image](https://user-images.githubusercontent.com/26231761/231936278-bcd3de44-16b0-4e2c-ad77-7e1121c26604.png)

**Comment by aamare1001** [comment]
I believe the issue is in api/trip/tripID/uid/purpose. for some reason the joinableEvents returned includes events already joined
![image](https://user-images.githubusercontent.com/26231761/231938214-3648eeee-53b3-4a2d-9c0b-6e68cc741103.png)

**Comment by Victoria-Williamson** [comment]
this was fixed in one of my branches
