### ISSUE TITLE
Containerize the application

### ISSUE THREAD

**Issue by jonathanhuydieu** [ucf-senior-design/senior-design#32]
In light of the issues with folks encountering issues with node and other dependency-related things, we should just package everything up into a container that can run our app and be updated  / shared between the group members.

- We'll probably use Docker to do this as it's the easiest and most straightforward option.

**Comment by Victoria-Williamson** [comment]
Before I close it, you finished it right? @jonathanhuydieu

**Comment by jonathanhuydieu** [comment]
Yep yep!!
