### ISSUE TITLE
Get foundation for sockets to work

### ISSUE THREAD

**Issue by jaeivan** [ucf-senior-design/senior-design#42]
Goals:
- Socket connects if user is logged in
- Join a "room" when you click on a document
- Emit changes to the document to others in the room (this can be an alert or something simple for the foundation) 

Perquisites:
- User can log in 
- Users can create trips which have UID's 
- Dashboard displays trips which are "joinable" and redirect user

**Comment by jaeivan** [comment]
Socket io vs Firebase
https://ably.com/compare/firebase-vs-socketio

**Comment by Victoria-Williamson** [comment]
we discovered websockets dont work with vercel :(
