### ISSUE TITLE
Mobile Application Section (Design Doc)

### ISSUE THREAD

**Issue by jonathanhuydieu** [ucf-senior-design/senior-design#8]
# Possible topics:
- Wireframe or Flow Diagram for the Mobile experience
- Mobile Frameworks (Flutter vs React Native)
- API reusability 
- Compare mobile feature suite to the web-application version

**Comment by Victoria-Williamson** [comment]
**Trip Page**
[Trip Page Modify/ Reschedule Event](https://www.figma.com/file/s94rnpDWKRvN9DCsR403AL/Mobile-Lofi?node-id=218%3A1819)
[Trip Page Event Has Been Changed](https://www.figma.com/file/s94rnpDWKRvN9DCsR403AL/Mobile-Lofi?node-id=218%3A1820)
[Algorithm: Time Slots for Rescheduling Event](https://www.figma.com/file/wBbNYkfZBabTejCLJdo6pe/Algorithm-%3A-Find-Open-Time-Slot?node-id=0%3A1)
[Flow for Trip Page] (https://www.figma.com/file/SEpyCCaajsUvQPBcMo2gkg/Untitled)
