### ISSUE TITLE
UI for modifying a trip

### ISSUE THREAD

**Issue by Victoria-Williamson** [ucf-senior-design/senior-design#91]

**Comment by aamare1001** [comment]
![image](https://user-images.githubusercontent.com/26231761/226214436-629d9b86-1a4b-4022-ae43-f3f7b411851a.png)

**Comment by aamare1001** [comment]
![image](https://user-images.githubusercontent.com/26231761/226214475-11776a65-ff78-46dd-a995-ca46fcdc5a89.png)
